name: educa
description: "A new Flutter project for LMS using Custom chatbot-Assistant and API in here of Django."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'

  #---------------------------packages----------------------------#
dependencies:
  flutter:
    sdk: flutter
    #----------------------Utility packages ----------------------
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  url_launcher: ^6.3.1
  intl: ^0.20.1
  iconsax: ^0.0.8
  connectivity_plus: ^6.1.0
  get_storage: ^2.1.1








  #icons







  #state management





  #product specific






  #Firebase







  #-------/packages end-------#



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true



  #-------Local Assets-----#
  assets:
     - assests/images/
     - assests/icons/
     - assests/images/cards/
     - assests/images/banners/
     - assests/images/faces/
     - assests/images/animations/

  #------LOCAL FONTS------#

  fonts:
     - family: Yekan
       fonts:
         - asset: assests/fonts/Yekan.woff
           weight: 800
           style: italic
         - asset: assests/fonts/Yekan.woff
           weight: 700
         - asset: assests/fonts/Yekan.woff
           weight: 600
         - asset: assests/fonts/Yekan.woff
           weight: 500
         - asset: assests/fonts/Yekan.woff
           weight: 400
         - asset: assests/fonts/Yekan.woff
           weight: 300
         - asset: assests/fonts/Yekan.woff
           weight: 200
         - asset: assests/fonts/Yekan.woff
           weight: 100
     - family: Inter
       fonts:
         - asset: assests/fonts/inter/Inter_24pt-ExtraBold.ttf
           weight: 900
         - asset: assests/fonts/inter/Inter_24pt-Bold.ttf
           weight: 800
         - asset: assests/fonts/inter/Inter_24pt-Bold.ttf
           weight: 700
         - asset: assests/fonts/inter/Inter_24pt-SemiBold.ttf
           weight: 600
         - asset: assests/fonts/inter/Inter_24pt-Medium.ttf
           weight: 500
         - asset: assests/fonts/inter/Inter_24pt-Regular.ttf
           weight: 400
         - asset: assests/fonts/inter/Inter_24pt-Light.ttf
           weight: 300
         - asset: assests/fonts/inter/Inter_24pt-Thin.ttf
           weight: 200
         - asset: assests/fonts/inter/Inter_24pt-Thin.ttf
           weight: 100



